/*
 * action constants
 */

export const DELETE_ARTICLE = "DELETE_ARTICLE"
export const CHANGE_SELECTION = "CHANGE_SELECTION"
export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"
