/*
 * action constants
 */

export const DELETE_ARTICLE = "DELETE_ARTICLE"
export const CHANGE_ARTICLE_SELECTION = "CHANGE_ARTICLE_SELECTION"
export const INCREMENT_COUNTER = "INCREMENT_COUNTER"
export const DECREMENT_COUNTER = "DECREMENT_COUNTER"

export const LOAD_ALL_COMMENTS = "LOAD_ALL_COMMENTS"
export const LOAD_ARTICLE_COMMENTS = "LOAD_ARTICLE_COMMENTS"
export const LOAD_COMMENT = "LOAD_COMMENT"
export const ADD_COMMENT = "ADD_COMMENT"

export const LOAD_ALL_ARTICLES = "LOAD_ALL_ARTICLES"
export const LOAD_ARTICLE = "LOAD_ARTICLE"

export const START = "_START"
export const SUCCESS = "_SUCCESS"
export const FAIL = "_FAIL"
